# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "iampaul83's blog"
email: "iampaul783@gmail.com"
description: >
  This is iampaul83's blog
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog

ampurl:    "https://cdn.ampproject.org/c/s/iampaul83.github.io" # the base hostname & protocol for your site
ampimgurl: "https://cdn.ampproject.org/i/s/iampaul83.github.io"
url: "https://iampaul83.github.io" # the base hostname & protocol for your site
realurl: "https://iampaul83.github.io" # the base hostname & protocol for your site

paginate:	5 # The number of posts to show per page on your homepage

name: 'iampaul83'
bio: >
  iampaul83 is a programmer
author_image: "/assets/images/author.jpg"
# twitter_username: jekyllrb
github_username:  iampaul83

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - octopress-autoprefixer
